root: true
env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  object-curly-spacing:
    - warn
    - always
  comma-dangle:
    - error
    - always-multiline
  eol-last:
    - warn
  indent:
    - warn
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - error
    - never
  newline-per-chained-call:
    - warn
    - ignoreChainWithDepth: 2
